In [1]:
import numpy as np

In [2]:
print("NumPy loaded successfully!")

NumPy loaded successfully!


In [3]:
print("NumPy version:", np.__version__)

NumPy version: 2.4.3


In [10]:
import time

In [11]:
python_list = list(range(1000000)) 

In [12]:
numpy_array = np.array(range(1000000))

In [13]:
start = time.time()           
result = []
for number in python_list:
    result.append(number * 2)  # multiply each number by 2 one by one

end = time.time()             # note the end time

python_time = end - start
print("Normal Python time:", round(python_time, 4), "seconds")


Normal Python time: 0.1994 seconds


In [14]:
start = time.time()           # note the start time

result = numpy_array * 2      # multiply ALL numbers at once

end = time.time()             # note the end time

numpy_time = end - start
print("NumPy time:", round(numpy_time, 4), "seconds")

# ------- How much faster? -------
print("NumPy is", round(python_time/numpy_time), "times faster!")

NumPy time: 0.0535 seconds
NumPy is 4 times faster!


In [19]:
a=np.array([1,2,3,4,5])
print("1D array:", a)
b=np.array([[1,2,3],
           [4,5,6]])
print("2D array:\n", b)
c=np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print("3D array:\n", c)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
print("shape of a:" , a.shape)
print("shape of b:", b.shape)
print("shape of c:", c.ndim)

shape of a: (5,)
shape of b: (2, 3)
shape of c: 3


In [27]:
print("Dimensions of a:", a.ndim)
print("dimensions of b:", b.ndim)
print("dimensions of c:", c.ndim)

Dimensions of a: 1
dimensions of b: 2
dimensions of c: 3


In [26]:
print("size of a:", a.size)
print("size of b:",b.size)
print("size of c:", c.size)

size of a: 5
size of b: 6
size of c: 8


In [25]:
print("datatype of a:", a.dtype)
print("datatype of b:", b.dtype)
print("datatype of c:",c.dtype)

datatype of a: int64
datatype of b: int64
datatype of c: int64


In [29]:
print("original dtype:",a.dtype)
print("original array:",a)

original dtype: int64
original array: [1 2 3 4 5]


In [33]:
# convert to float - what ML models need

a_float=a.astype(float)
print("\nAfter creating in float:")
print("new dataype:",a_float.dtype)
print("new array:",a_float)


After creating in float:
new dataype: float64
new array: [1. 2. 3. 4. 5.]
