In [4]:
import numpy as np


In [10]:
# np.zeros - array filled with all zeros
a = np.zeros((3, 4))
print("Zeros array:")
print(a)
print()

Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
print("Shape:", a.shape)
print("dtype:", a.dtype)

print()

Shape: (3, 4)
dtype: float64


In [5]:
# np.ones - array filled with all ones
b = np.ones((2, 3))
print("Ones array:")
print(b)
print("Shape:", b.shape)
print("dtype:", b.dtype)

Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]
Shape: (2, 3)
dtype: float64


In [16]:
# arange
c = np.arange(0, 10, 2)
print("Arange array:")
print(c)
print()
print("dtype:", c.dtype)


Arange array:
[0 2 4 6 8]

dtype: int64


In [10]:
# linspace
d = np.linspace(0, 1, 5)
print("Linspace array:")
print(d)
print()
print("dtype:", d.dtype)

Linspace array:
[0.   0.25 0.5  0.75 1.  ]

dtype: float64


In [18]:
# random
e = np.random.randn(3, 3)
print("Random array:")
print(e)
print("Shape:", e.shape)
print("dtype:", e.dtype)

Random array:
[[-0.31682954 -1.00123129 -0.39380492]
 [ 0.30708687  1.08241283  0.55746983]
 [-0.21550352 -0.39705     0.1430613 ]]
Shape: (3, 3)
dtype: float64


In [12]:
# Real neural network training loop simplified:

# 1. Initialize weights randomly
weights = np.random.randn(784, 128)
print(weights)

[[ 0.97182887 -1.14397861  0.94541939 ...  0.51371915 -0.15294928
  -0.54638119]
 [-0.54975663 -0.09511299 -0.10310204 ... -0.49633481 -1.50891759
   0.4618005 ]
 [-1.17337046 -1.74264063 -2.29790145 ... -0.29015676  1.46591767
  -0.05264609]
 ...
 [-0.69739616  0.18086469  0.41800813 ...  0.121258    0.85557368
   1.24627561]
 [-0.40569497  0.17524411  1.04517154 ...  0.70010821 -0.67643537
   1.06766827]
 [-0.90813926 -1.64007494  0.86355005 ... -0.82546536 -0.34704553
   1.33261368]]


In [14]:
# 2. Create empty array to store losses
losses = np.zeros(100)
print(losses)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [16]:
# 3. Create indices to shuffle dataset
indices = np.arange(60000)  # 60000 training images
np.random.shuffle(indices)  # shuffle randoml
print(indices)


[26983 12227 59577 ...  1272 58715 16688]


In [17]:
# 4. Find best learning rate
learning_rates = np.linspace(0.0001, 0.1, 5)
print(learning_rates)


[0.0001   0.025075 0.05005  0.075025 0.1     ]


for epoch in range(100):

    current_loss = 0

    for i in range(0, 60000, 32):

        batch = indices[i:i+32]

        batch_loss = np.random.random()

        current_loss += batch_loss

    current_loss /= (60000 // 32)

    losses[epoch] = current_loss

print(losses)

But What if You Want SAME Random Numbers Every Time?
Sometimes in ML you want reproducible results:
You train a model and get 95% accuracy
Your friend runs same code and gets 93%
Why different? Random initialization!

You want SAME results every time
So you can compare fairly

In [33]:
# Without seed - different every time
print(np.random.randn(3))
print(np.random.randn(3))
# Different numbers!


[ 0.67632998 -0.20849781  1.16877851]
[ 0.3061682  -2.08518162 -1.36956919]


In [34]:
# With seed - same every time!
np.random.seed(42)
print(np.random.randn(3))


[ 0.49671415 -0.1382643   0.64768854]


In [35]:
np.random.seed(42)
print(np.random.randn(3))
# Same numbers every time!

[ 0.49671415 -0.1382643   0.64768854]


In [37]:
np.random.seed(42)
print(np.random.randn(3))
print()

[ 0.49671415 -0.1382643   0.64768854]



In [38]:
# Dot meaning
print("Integer array (no dots):", np.array([1,2,3]))
print("Float array (with dots):", np.zeros(3))


Integer array (no dots): [1 2 3]
Float array (with dots): [0. 0. 0.]


In [39]:
# Tuple vs no tuple
print("--- Tuple Test ---")
a = np.zeros((3, 4))
print("With tuple works:", a.shape)


--- Tuple Test ---
With tuple works: (3, 4)


In [40]:
# Masking
print("\n--- Masking ---")
data = np.array([10, 20, 30, 40, 50])
mask = np.array([1, 0, 1, 0, 1])
result = data * mask
print("Original data:", data)
print("Mask:", mask)
print("After masking:", result)


--- Masking ---
Original data: [10 20 30 40 50]
Mask: [1 0 1 0 1]
After masking: [10  0 30  0 50]


In [41]:
# Broadcasting
print("\n--- Broadcasting ---")
a = np.array([1, 2, 3, 4, 5])
print("Original:", a)
print("After adding 10:", a + 10)


--- Broadcasting ---
Original: [1 2 3 4 5]
After adding 10: [11 12 13 14 15]


In [42]:
b = np.ones((3, 3))
c = np.array([1, 2, 3])
print("\nones array:\n", b)
print("row array:", c)
print("after broadcasting:\n", b + c)


ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
row array: [1 2 3]
after broadcasting:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
