In [1]:
import numpy as np


In [10]:
# np.zeros - array filled with all zeros
a = np.zeros((3, 4))
print("Zeros array:")
print(a)
print()

Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
print("Shape:", a.shape)
print("dtype:", a.dtype)

print()

Shape: (3, 4)
dtype: float64


In [5]:
# np.ones - array filled with all ones
b = np.ones((2, 3))
print("Ones array:")
print(b)
print("Shape:", b.shape)
print("dtype:", b.dtype)

Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]
Shape: (2, 3)
dtype: float64


In [16]:
# arange
c = np.arange(0, 10, 2)
print("Arange array:")
print(c)
print()
print("dtype:", c.dtype)


Arange array:
[0 2 4 6 8]

dtype: int64


In [17]:
# linspace
d = np.linspace(0, 1, 5)
print("Linspace array:")
print(d)
print()
print("dtype:", d.dtype)

Linspace array:
[0.   0.25 0.5  0.75 1.  ]

dtype: float64


In [18]:
# random
e = np.random.randn(3, 3)
print("Random array:")
print(e)
print("Shape:", e.shape)
print("dtype:", e.dtype)

Random array:
[[-0.31682954 -1.00123129 -0.39380492]
 [ 0.30708687  1.08241283  0.55746983]
 [-0.21550352 -0.39705     0.1430613 ]]
Shape: (3, 3)
dtype: float64
